### ISSUE TITLE
In video background remover replicate 

### ISSUE THREAD

**Issue by tahercoolguy** [nateraw/replicate-examples#2]
In video background remover replicate . I have successful deployed on replicate through your code . But at the runtime i am getting this error 

Prediction failed.

torch.cat(): expected a non-empty list of Tensors

`0 0.0 - 1.5
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 25, in predict
out = self.pipe(str(video), chunk_duration=1.5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/src/pipeline.py", line 153, in __call__
full_processed_video = torch.cat(processed_video_clips, dim=1)  # Assuming dim=1 is the time dimension
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors

`

And above is snippet

Can you please help what problem it can be

**Comment by nateraw** [comment]
Could it be a bad input file? Have you tried any of the example files that are in the demo I put on replicate?

**Comment by nateraw** [comment]
This one for example https://huggingface.co/spaces/nateraw/animegan-v2-for-videos/resolve/main/obama.webm

**Comment by tahercoolguy** [comment]
Thanks for it . I will try .

**Comment by tahercoolguy** [comment]
I have used above link i am getting decoding error "Unable to decode video stream"
